### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by knownasilya** [comment]
Ping :smile:

**Comment by omghax** [comment]
@knownasilya I updated the readme with the 1.2.0 release. Thanks for the PR :)

**Comment by knownasilya** [comment]
Since 1.2 uses block params, is that a breaking change for anyone using 1.1.0 with a ^ or ~?

**Comment by omghax** [comment]
It shouldn't be...if you don't specify the block params it falls back to using the old `parentView` behavior, but also emits a deprecation warning. Once I remove the deprecations I'll bump the major version.

**Pull request closed without merging**
