### PR TITLE
Move to modules API

### PR DESCRIPTION
**Pull request by YoranBrondsema**
Depends on https://github.com/IvyApp/ivy-tabs/pull/36

* Moves to the modules API
* Removes `ember-cli-shims` dependency

### CODE REVIEW

**Comment by lolmaus** [comment]
Thank you! :bow:

The upstream seems unmaintained. Can you please mark the `module-unification` as protected on your fork since we're gonna depend on it?

**Comment by YoranBrondsema** [comment]
@lolmaus No problem, done.

@omghax Can you clarify the status of this addon? Will you accept pull requests? Or is it best we fork it?

**Comment by nbibler** [comment]
Thank you for removing the shims! :)

**Comment by YoranBrondsema** [comment]
Thanks for merging!

**Pull request merged**
